# Generated by Django 3.0.3 on 2020-07-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_price', models.IntegerField(max_length=50)),
                ('crawl_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
