# Generated by Django 3.0.3 on 2020-07-06 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='p_site',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
