# Generated by Django 3.0.3 on 2020-07-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_product_info_p_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='p_price',
            field=models.IntegerField(default=0),
        ),
    ]
